version: '3.8'

services:
  dnsmasq:
    build: ./dnsmasq
    container_name: dnspooq-dnsmasq
    networks:
      dnspooq:
        ipv4_address: 10.10.0.2
    environment:
      - CACHE_IP=192.168.115.151
    ports:
      - "53:53/udp"
    cap_add:
      - NET_ADMIN
    
  attacker:
    build: ./attacker
    container_name: dnspooq-attacker
    networks:
      dnspooq:
        ipv4_address: 10.10.0.3
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - ./attacker:/app
    
  client:
    build: ./client
    container_name: dnspooq-client
    networks:
      dnspooq:
        ipv4_address: 10.10.0.6
    ports:
      - "6080:80"
    dns:
      - 10.10.0.2
    environment:
      - VNC_PASSWORD=password
    volumes:
      - /dev/shm:/dev/shm

networks:
  dnspooq:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.0.0/24
