name: Create and publish container images

on:
  push:
    branches: ["main", "lab"]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository_owner }}/security-lab-1

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        include:
          - service: attacker
          - service: client
          - service: dnsmasq
          - service: cache
            skip_on_lab: true
          - service: malicious-server
            skip_on_lab: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check if service directory exists
        id: check-dir
        run: |
          if [ "${{ github.ref_name }}" = "lab" ] && [ "${{ matrix.skip_on_lab }}" = "true" ]; then
            echo "skip=true" >> $GITHUB_OUTPUT
          elif [ -d "${{ matrix.service }}" ]; then
            echo "skip=false" >> $GITHUB_OUTPUT
          else
            echo "skip=true" >> $GITHUB_OUTPUT
          fi

      - name: Set up Docker Buildx
        if: steps.check-dir.outputs.skip != 'true'
        uses: docker/setup-buildx-action@v3

      - name: Log into registry ${{ env.REGISTRY }}
        if: steps.check-dir.outputs.skip != 'true'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        if: steps.check-dir.outputs.skip != 'true'
        id: build-and-push
        uses: docker/build-push-action@v6
        with:
          context: ./${{ matrix.service }}
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ matrix.service }}-latest